language: generic

env:
  - BUILD_TYPE=RELEASE
  - BUILD_TYPE=DEBUG

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
    exclude:
        - os: osx
          compiler: gcc
        - os: linux
          compiler: clang

addons:
    apt:
      sources:
        - george-edison55-precise-backports
      packages:
        - cmake
        - cmake-data
        - valgrind
        - python-numpy
        - python-matplotlib

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip install --user matplotlib;
    fi

before_script:
  # Valgrind is experimental(ish) on MacOS with false positives on among others printf
  #- if [[ "$TRAVIS_OS_NAME" == "osx" && "$BUILD_TYPE" == "DEBUG" ]]; then
  #    brew update;
  #    brew install --HEAD valgrind;
  #  fi

  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - export LD_LIBRARY_PATH=$PWD

script: make && ctest --output-on-failure
